---
- name: ClusterColombia HTC Condor CM role playbook
  
  hosts: all

  become: yes

  vars:
    write_collector_nodes: "en1 en2 sn"   # TODO: move to vars + automate

  tasks:

    # Install OpenVPN

    - name: Install OpenVPN
      yum:
        name: openvpn
        state: latest

    # Set the node's role

    - name: Check if the node's role already has been set
      lineinfile:
        state: absent
        path: /etc/condor/config.d/51-role-cm
        line: "use ROLE: CentralManager"
      check_mode: true
      changed_when: false
      register: check

    - name: Set the node's role if it has not been set before
      lineinfile:
        state: present
        path: /etc/condor/config.d/51-role-cm
        line: "use ROLE: CentralManager"
        create: yes
        backup: yes
      when: check.msg == "file not present" or check.found == 0

    # Allow write collector

    - name: Check if the permission has already been set
      lineinfile:
        state: absent
        path: /etc/condor/config.d/51-role-cm
        line: "ALLOW_WRITE_COLLECTOR=$(ALLOW_WRITE) {{ write_collector_nodes }}"
      check_mode: true
      changed_when: false
      register: check

    - name: Set the node's role if it has not been set before
      lineinfile:
        state: present
        path: /etc/condor/config.d/51-role-cm
        line: "ALLOW_WRITE_COLLECTOR=$(ALLOW_WRITE) {{ write_collector_nodes }}"
        create: yes
        backup: yes
      when: check.msg == "file not present" or check.found == 0

    # Restart the HTC Condor's service

    - name: Restart the HTC Condor's service
      ansible.builtin.service:
        name: condor
        state: restarted