---
- name: ClusterColombia compile Virtualbox Addons
  
  hosts: all

  become: yes

  # config.vm.provision "fix_vboxsf", run: "never", type: "ansible" do |ansible|
  #   ansible.playbook = "./ansible/vbox_addons.playbook.yml"
  # end

  tasks:
    # install required software

    - name: install required software
      yum:
        name:
          - gcc
          - make
          - perl
        state: latest

    # Compile module for all available kernels

    - name: Compile module for all available kernels
      command: "/sbin/rcvboxadd quicksetup all"
